# Generated by Django 5.1.1 on 2024-10-22 04:26

import autoslug.fields
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category_name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField(default='product description')),
                ('product_price', models.PositiveIntegerField(default=0)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_brand', models.CharField(default='superpet', max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categories')),
            ],
            managers=[
                ('aradhya', django.db.models.manager.Manager()),
            ],
        ),
    ]
